language: node_js
node_js:
  - "8"
script:
  - npm run lint
  - npm run test -- --ci --coverage --coverageReporters=text-lcov | coveralls
  - npm run test -- --ci --bail
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  - /^greenkeeper.*$/
